### ISSUE TITLE
BUG - Temp Block Not working

### ISSUE THREAD

**Issue by iMxAndyy** [Indyuce/mmocore#33]
When setup correctly, breaking blocks does not change the block to the temp block that is defined. 
The block just breaks. And then regen's after the defined time.

**Comment by Indyuce** [comment]
Please pastebin the temp block config file you used to reproduce the issue and the MMOCore build you are using. This config worked fine on my end
```
on-mine:
    emerald:
        material: EMERALD_ORE
        drop-table:
            items:
            - 'vanilla{type=EMERALD} 1 1-9'
        vanilla-drops: false
        regen:
            time: 2000
            temp-block: STONE
        triggers:
        - 'exp{profession=mining;amount=32}'

    diamond:
        # The material you need to mine
        material: DIAMOND_ORE
        
        regen:
        
            # Ticks the block takes to appear again
            time: 20
            
            # The temporary block which shows
            # during the block regen time.
            #
            # !! Warning !!
            # When using the temp-block option, make sure you choose
            # one temp block and don't use it anywhere else in the
            # configuration so that block regens do not affect each other
            temp-block: STONE
```
