### ISSUE TITLE
[Suggestion] Effect depending on the level of a Mythicmobs

### ISSUE THREAD

**Issue by Kalorte** [Indyuce/mmocore#50]
Hello,

Here's another suggestion, making the MMOCore plugin even more correlated with MythicMobs.
This would be an option that would define several things according to the level difference (higher or lower) between the Player and the MM:
- % of XP given
- % chance of hitting the monster
- % extra money  ...
This can be an increase or decrease.

An example of a configuration:

level-difference:
```
  - >3: 
    - exp-multiplier: 50%
    - hit-chance: -60%
    - money-multiplier: 50%
  - 2:
    - exp-multiplier: 50%
    - hit-chance: -60%
    - money-multiplier: 50%
  - 1: 
    - exp-multiplier: 50%
    - hit-chance: -60%
    - money-multiplier: 50%
  - 0:
    - exp-multiplier: 0%
    - hit-chance: 0%
    - money-multiplier: 0%
  - 1: 
    - exp-multiplier: -20%
    - hit-chance: +200%
    - money-multiplier: 0%
  - 2:
    - exp-multiplier: -30%
    - hit-chance: +30%
    - money-multiplier: 0%
  - <3:
    - exp-multiplier: -90%
    - hit-chance: +90%
    - money-multiplier: 0%
```
