### ISSUE TITLE
[Bug] Referencing a drop table no longer works in my professions

### ISSUE THREAD

**Issue by iMxAndyy** [Indyuce/mmocore#56]
`[07:28:43] [Server thread/WARN]: [MMOCore] Could not load drop item 'droptable{id=gems-and-ores} .1' from table 'drop-table': Could not load 'droptable{id=gems-and-ores} .1': Could not find drop table gems-and-ores`

I'm getting this error when i load up the plugin

My profession is setup like this
```
redstone:
        material: vanilla{type=REDSTONE_ORE}
        vanilla-drops: false
        drop-table:
            items:
            - 'droptable{id=gems-and-ores} .1'
```
Which has worked previously

And the drop table still exists
```
gems-and-ores:
    items:
    - 'mmoitem{type=material;id=AMETHYST} 0.3 1-1'
    - 'mmoitem{type=material;id=CITRITE} 0.3 1-1'
    - 'mmoitem{type=material;id=ONYX} 0.3 1-1'
    - 'mmoitem{type=material;id=RUBY} 0.3 1-1'
    - 'mmoitem{type=material;id=AMBER} 0.3 1-1'
    - 'mmoitem{type=material;id=JADE} 0.3 1-1'
    - 'mmoitem{type=miscellaneous;id=DIAMOND} 1 1-1'
    - 'mmoitem{type=miscellaneous;id=EMERALD} 1 1-1'
    - 'mmoitem{type=miscellaneous;id=GOLD} 1 1-1'
    - 'mmoitem{type=miscellaneous;id=COAL} 1 1-1'
    - 'mmoitem{type=miscellaneous;id=IRON} 1 1-1'
```

But it can't seem to find it. And the error message seems to imply that it thinks the drop table is an item rather than a drop table. so I assume something in how this is formatted has changed
